package com.neko.hiepdph.dynamicislandvip.common

import com.neko.hiepdph.dynamicislandvip.BuildConfig

object Constant {
    const val UPDATE_LAYOUT_SIZE = "UPDATE_LAYOUT_SIZE"
    const val KEY_MARGIN_HORIZONTAL = "KEY_MARGIN_HORIZONTAL"
    const val KEY_MARGIN_VERTICAL = "KEY_MARGIN_VERTICAL"
    const val KEY_NOTCH_STYLE = "KEY_NOTCH_STYLE"
    const val KEY_WIDTH = "KEY_WIDTH"
    const val KEY_HEIGHT = "KEY_HEIGHT"
    const val APP_DB = "APP_DB_DYNAMIC"
    const val KEY_BACKGROUND_DYNAMIC_ALPHA = "KEY_BACKGROUND_DYNAMIC_ALPHA"
    const val KEY_BACKGROUND_DYNAMIC_COLOR = "KEY_BACKGROUND_DYNAMIC_COLOR"
    const val KEY_SIZE_BORDER = "KEY_SIZE_BORDER"
    const val KEY_BUBBLE_BACKGROUND_COLOR = "KEY_BUBBLE_BACKGROUND_COLOR"
    const val KEY_ALPHA_VAL_BORDER = "KEY_ALPHA_VAL_BORDER"
    const val KEY_ALPHA_VAL_BACKGROUND = "KEY_ALPHA_VAL_BACKGROUND"
    const val KEY_BUBBLE_DISPLAY_TIME = "KEY_BUBBLE_DISPLAY_TIME"
    const val KEY_BUBBLE_LOCATION = "KEY_BUBBLE_LOCATION"
    const val KEY_BUBBLE_FREQ = "KEY_BUBBLE_FREQ"
    const val KEY_SHOW_BUBBLE_BORDER = "KEY_SHOW_BUBBLE_BORDER"
    const val KEY_SHOW_BUBBLE_COLOR = "KEY_SHOW_BUBBLE_COLOR"
    const val KEY_SHOW_BUBBLE = "KEY_SHOW_BUBBLE"
    const val KEY_COLOR_ANIM = "KEY_COLOR_ANIM"
    const val KEY_ALPHA_VAL = "KEY_ALPHA_VAL"
    const val KEY_CLICK_MODE = "KEY_CLICK_MODE"
    const val TIME_SHOW_RATE = "TIME_SHOW_RATE"
    const val KEY_USER_RATED = "KEY_USER_RATED"
    const val KEY_FROM_MAIN = "KEY_FROM_MAIN"
    const val KEY_CALL_TIMER = "KEY_CALL_TIMER"
    const val KEY_SHOW_DEFAULT = "KEY_SHOW_DEFAULT"
    const val KEY_INCOMING_CALL = "KEY_INCOMING_CALL"
    const val KEY_NOTIFICATION_ICON = "KEY_NOTIFICATION_ICON"
    const val KEY_NOTIFICATION_SHOW_ACTION = "KEY_NOTIFICATION_SHOW_ACTION"
    const val KEY_NOTIFICATION_HIDE_ON_LOCK_SCREEN = "KEY_NOTIFICATION_HIDE_ON_LOCK_SCREEN"
    const val KEY_NOTIFICATION_QUICK_PLAY = "KEY_NOTIFICATION_QUICK_PLAY"
    const val KEY_LANGUAGE = "KEY_LANGUAGE"
    const val KEY_NOTIFICATION_ANIMATION = "KEY_NOTIFICATION_ANIMATION"
    const val KEY_DISPLAY_MODE = "KEY_DISPLAY_MODE"
    const val KEY_NOTIFICATION_ENABLE = "KEY_NOTIFICATION_ENABLE"
    const val KEY_CALL_ENABLE = "KEY_CALL_ENABLE"
    const val KEY_MUSIC_ENABLE = "KEY_MUSIC_ENABLE"
    const val KEY_EARPHONE_ENABLE = "KEY_EARPHONE_ENABLE"
    const val KEY_BATTERY_CHARGE_ENABLE = "KEY_BATTERY_CHARGE_ENABLE"
    const val KEY_RINGING_STATE_ENABLE = "KEY_RINGING_STATE_ENABLE"
    const val KEY_DIRECT_ENABLE = "KEY_DIRECT_ENABLE"
    const val URL_APP =
        "https://play.google.com/store/apps/details?id=${BuildConfig.APPLICATION_ID}"

    const val URL_PRIVACY = "https://sites.google.com/view/cheerupprivacy/home"


    const val TYPE_AIRBUDS: String = "TYPE_AIRBUDS"

    const val TYPE_CHARGING: String = "CAT_CHARGING"

    const val TYPE_SILENT: String = "CAT_SILENT"

    const val USE_MATERIAL_COLOR: String = "USE_MATERIAL_COLOR"

    const val WALLPAPER_COLOR: String = "WALLPAPER_COLOR"

    const val WALLPAPER_UPDATED: String = "WALLPAPER_UPDATED"

}